In [1]:
import pandas as pd

In [2]:
hero_powers = pd.read_csv('superhero_powers.csv')
hero_powers

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
663,Ymir,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
664,Yoda,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
665,Zatanna,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
666,Zoom,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
hero_dc = pd.read_excel('superhero_info.xlsx', sheet_name = 'DC Comics')
hero_marvel = pd.read_excel('superhero_info.xlsx', sheet_name = 'Marvel Comics')

In [4]:
hero_marvel.head()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Alignment,Weight
0,A-Bomb,Male,yellow,Human,No Hair,203,Marvel Comics,good,441
1,Abomination,Male,green,Human / Radiation,No Hair,203,Marvel Comics,bad,441
2,Abraxas,Male,blue,Cosmic Entity,Black,-99,Marvel Comics,bad,-99
3,Absorbing Man,Male,blue,Human,No Hair,193,Marvel Comics,bad,122
4,Agent 13,Female,blue,-,Blond,173,Marvel Comics,good,61

In [5]:
df = pd.read_csv('weather.csv')
df

,date,temperature_high,temperature_low,rained,snowed,overcast,comments
0,2021-01-01,4.0,1,1,False,cloudy,happy new year
1,2021-01-02,11.0,2,0,False,sunny,second day
2,2021-01-03,3.0,2,0,False,foggy,third day
3,2021-01-04,6.0,2,0,False,sunny,first business day
4,2021-01-05,4.0,unknown,0,False,cloudy,second business day

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      object
 1   temperature_high  5 non-null      float64
 2   temperature_low   5 non-null      object
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      object
 6   comments          5 non-null      object
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 377.0+ bytes

In [7]:
df['temperature_high'] = df['temperature_high'].astype('int8')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      object
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      object
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      object
 6   comments          5 non-null      object
dtypes: bool(1), int64(1), int8(1), object(4)
memory usage: 342.0+ bytes

In [9]:
df['temperature_high']

0     4
1    11
2     3
3     6
4     4
Name: temperature_high, dtype: int8

In [10]:
df['rained'] = df['rained'].astype('bool')
df['rained']

0     True
1    False
2    False
3    False
4    False
Name: rained, dtype: bool

In [11]:
df = df.astype({'overcast' : 'category', 'comments' : 'string'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      object
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      object
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      category
 6   comments          5 non-null      string
dtypes: bool(2), category(1), int8(1), object(2), string(1)
memory usage: 404.0+ bytes

In [12]:
df['overcast']

0    cloudy
1     sunny
2     foggy
3     sunny
4    cloudy
Name: overcast, dtype: category
Categories (3, object): ['cloudy', 'foggy', 'sunny']

In [13]:
df['temperature_low'] = pd.to_numeric(df['temperature_low'], errors= 'coerce')

In [14]:
df['temperature_low']

0    1.0
1    2.0
2    2.0
3    2.0
4    NaN
Name: temperature_low, dtype: float64

In [15]:
df['date'] = pd.to_datetime(df['date'])

In [16]:
df['date']

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
Name: date, dtype: datetime64[ns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      datetime64[ns]
 1   temperature_high  5 non-null      int8
 2   temperature_low   4 non-null      float64
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      category
 6   comments          5 non-null      string
dtypes: bool(2), category(1), datetime64[ns](1), float64(1), int8(1), string(1)
memory usage: 404.0 bytes

In [18]:
hero_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Columns: 168 entries, hero_names to Omniscient
dtypes: bool(167), object(1)
memory usage: 114.1+ KB

In [19]:
hero_powers.head()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
hero_powers['hero_names'] = hero_powers['hero_names'].astype('string')

In [21]:
hero_dc.dtypes

name           object
Gender         object
Eye color      object
Race           object
Hair color     object
Height          int64
Publisher      object
Alignment      object
Weight        float64
dtype: object

In [22]:
hero_dc.head()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Alignment,Weight
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0
3,Alfred Pennyworth,Male,blue,Human,Black,178,DC Comics,good,72.0
4,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0

In [ ]:
hero_dtype = {'Name' : 'string', 'Gender': 'category', 'Eye color' : 'string', 'Race' : 'string', 'Hair color' : 'string', 'Publisher' : 'string', 'Alignment' : 'category'}

In [36]:
hero_dc.dtypes()

TypeError: 'Series' object is not callable