In [1]:
import pandas as pd

In [2]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [4]:
index_day = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
data = [1,2,3,4,5,6,7]

In [7]:
s = pd.Series(data, index = index_day)
s

monday       1
tuesday      2
wednesday    3
thursday     4
friday       5
saturday     6
sunday       7
dtype: int64

In [8]:
s.mean()

np.float64(4.0)

In [9]:
df = pd.DataFrame({"first": s, "second" : s * 2, "third" : s *  5})
df

           first  second  third
monday         1       2      5
tuesday        2       4     10
wednesday      3       6     15
thursday       4       8     20
friday         5      10     25
saturday       6      12     30
sunday         7      14     35

In [10]:
coloumn_names = ['city', 'population']
index_country = [ 'japan', 'india', 'china', 'brazil', 'mexico']

In [12]:
row1 = ['tokyo' , 37.4]
row2 = ['delhi' , 28.5]
row3 = ['shangai' , 27.5]
row4 = ['sau pailo' , 21.5]
row5 = ['mexico city' , 21.6]
data = [row1, row2, row3, row4, row5]

In [13]:
df = pd.DataFrame(data, index = index_country, columns = coloumn_names)
df

               city  population
japan         tokyo        37.4
india         delhi        28.5
china       shangai        27.5
brazil    sau pailo        21.5
mexico  mexico city        21.6

In [16]:
cities = ['tokyo', 'mumbai', 'shnagai', 'rio', 'mexico city']
population = [28.3, 25.6, 45.5, 23.5, 54.3]
popu_dict = {'city' : cities, 'population' : population}

In [17]:
df = pd.DataFrame(popu_dict, index = index_country)
df

               city  population
japan         tokyo        28.3
india        mumbai        25.6
china       shnagai        45.5
brazil          rio        23.5
mexico  mexico city        54.3